export  interface IasbestosCertificate{
  pin: string,
  qrURL: string,
  ExamStatus: string,
  ApprovalStatus: string,
  Certificatenumber: string,
  FirstName: string,
  LastName: string,
  Gender: string,
  CertificateType: string,
  Photolink: string,
  Token: string,
  Address: string,
  ApplicationType: string,
  expiresOn: string,
  OldCertficateType: string,
  checkstatus: false,
  certificateId: string,
  status: string,
  message: string,
  scanningStatus: string,
  reqId: string,
  oldReqId: string,
  statusMessage:string
  //statusMessage: "Please wait!",
  selectedCertificateType: [],
  IsApplicationValid: false,
  certificateTypeValues:any[],
  disableDropdown:boolean,
  duplicateExpiryDate:string,
  hideqr:boolean
}
