export interface Idashboard {
  applicantFirstName: string,
  applicantMiddleName: string,
  applicantLastName: string,
  applicantDOB: Date,
  applicationType: string,
  applicantDMVNumber: number,
  certificateType: string,
  examSlotDate: string,
  loginUserEmailId: string,
  submittedOn: Date,
  paymentResponseXML: number,
  status: string,
  ocseStatus: string,
  examStatus: string,
  applicantGender: string,
  applicantHeight: number,
  applicantState: string,
  applicantWeight: number,
  applicantZipCode: number,
  homeTelephoneNumber: number,
  employerStreetAddress: string,
  employerZipcode: number,
  employerState: string,
  employerCity: string,
  currentEmployerName: string,
  applicantCity: string,
  applicantApartment: string,
  applicantAddress: string,
  paymentStatus:string,
  photoLink:URL
}
